import { AccentColor, ExperienceItem, ProjectItem, SkillItem } from '@/types/types';
import { Facebook, Github, Linkedin, Mail } from 'lucide-react';

export const NAMES = ['Darl Ellison Floresca', 'Darl Floresca', 'Eli Floresca', 'Ellison Floresca'];
export const INTERESTS = ['Football', 'League of Legends'];
export const EXPLORING = ['AI Engineering', 'Cloud Computing'];
export const EDUCATION = {
  university_attended: 'Bulacan State University',
  location: 'Malolos City, Bulacan',
  course: 'Bachelor of Science in Information Technology',
  date_started: 'Aug 2022',
  date_graduated: 'Jun 2026',
  gpa: 1.71,
};

export const PERSONAL_DATA = {
  short_introduction:
    'I am a BSIT graduate of Bulacan State University (Malolos) currently working as a Custom Software Engineer at Accenture. As a highly coachable developer, I thrive on constructive feedback and industry-best practices to continuously sharpen my skills. I bring rigorous, hands-on project experience and a strict commitment to maintaining high standards for code scalability and performance. I am eager to leverage my adaptable mindset and strong technical foundation within a dynamic development team.',
  names: NAMES,
  based_in: 'Marilao, Bulacan, Philippines',
  education: EDUCATION,
  emails: ['floresca.darlellisong@gmail.com', 'darlellisonf@gmail.com'],
  age: '23 years old',
  birthdate: 'December 16, 2002',
  github: { username: 'elli1216', link: 'https://github.com/elli1216' },
  linkedid: {
    name: 'Darl Ellison Floresca',
    link: 'https://www.linkedin.com/in/darlfloresca',
  },
  interests: { INTERESTS, EXPLORING },
};

export const category = {
  ACADEMIC: 'Academic Project',
  PERSONAL: 'Personal Project',
  CAPSTONE: 'Capstone Project',
  FREELANCE: 'Freelance',
  HACKATHON: 'Hackathon Project',
};

export const ACCENT_COLORS: AccentColor[] = [
  { name: 'green', value: '#2da44e' },
  { name: 'blue', value: '#2563eb' },
  { name: 'red', value: '#e63946' },
  { name: 'orange', value: '#ea580c' },
  { name: 'purple', value: '#9333ea' },
  { name: 'gray', value: '#6e7781' },
];

export const NAV_ITEMS = [
  { label: 'About Me', href: '#about' },
  { label: 'Experience', href: '#experience' },
  { label: 'Projects', href: '#projects' },
  { label: 'Skills', href: '#skills' },
  { label: 'Certificates', href: '#certificates' },
  { label: 'Contact', href: '#contact' },
];

export const EXPERIENCE_DATA: ExperienceItem[] = [
  {
    role: 'Custom Software Engineer',
    company: 'Accenture',
    companyUrl: 'accenture.com',
    period: 'September 2026 - Present',
    location: 'NCR, Philippines | Hybrid',
    description: ['Onboarded as a Custom Software Engineer after 3 month training.'],
  },
  {
    role: 'Full Stack Development Trainee',
    company: 'Accenture Technology Academy',
    companyUrl: 'accenture.com',
    period: 'April 2026 - July 2026',
    location: 'Mandaluyong City, Philippines | Hybrid',
    description: [
      'Selected for an exclusive 343-hour intensive training program focused on Full Stack Development and Microservices.',
      'Mastered enterprise backend technologies including Core Java and Spring Boot.',
      'Developed responsive frontend applications utilizing modern ReactJS and TypeScript.',
    ],
    certificate: '/certificates/training.png',
  },
  {
    role: 'COBOL Developer Intern',
    company: 'Land Bank of the Philippines (HO)',
    companyUrl: 'landbank.com',
    period: 'February 2026 - April 2026',
    location: 'Malate, Manila, Philippines',
    description: [
      'Contributed to the migration and development of 10+ COBOL programs to z/OS mainframe for financial data processing.',
      'Worked with PS and VSAM input files to handle data reading, validation, and processing logic.',
      'Executed JCL job submissions and monitored execution status to maintain system reliability.',
      'Performed unit testing and ensured the programs complied with IBM z/OS coding standards to ensure seamless enterprise integration.',
    ],
    certificate: '/certificates/internship.png',
  },
  {
    role: 'Salesforce Developer Intern',
    company: 'The SmartBridge',
    companyUrl: 'thesmartbridge.com',
    period: 'March 2025 – May 2025',
    location: 'Philippines | Remote',
    description: [
      'Completed 22 intensive superbadges on Salesforce Trailhead through simulated real-world scenarios.',
      'Gained hands-on experience implementing core CRM concepts, security models, and workflow automation.',
      'Applied best practices for scalable system design utilizing various Salesforce cloud technologies.',
    ],
    certificate: '/certificates/salesforce.png',
  },
  {
    role: 'Institutional Student Assistant',
    company: 'Bulacan State University',
    companyUrl: 'bulsu.edu.ph',
    period: 'January 2025 – May 2025',
    location: 'Malolos City, Bulacan, Philippines',
    description: [
      'Managed daily front desk operations, document handling, and administrative tasks.',
      'Facilitated efficient communication and coordination between various university offices.',
      'Maintained high service standards while actively resolving student inquiries and concerns.',
    ],
  },
];

export const PROJECT_DATA: ProjectItem[] = [
  {
    title: 'MergeMaster AI',
    position: 'Full Stack & AI Developer',
    theme:
      "AI is evolving from a productivity tool into a true collaborator that can help people plan, coordinate, decide, and execute work more effectively. Build solutions that help individuals, teams, and organizations achieve better outcomes through intelligent automation, workflow orchestration, and decision support. Whether you're building workflow automation systems, AI co-workers, decision intelligence platforms, or business process orchestration tools, your project should demonstrate how AI can help transform work from disconnected tasks into intelligent, outcome-driven systems.",
    hackathonTitle: 'IBM AI Builders Challenge (Wild Card Category)',
    collaborators: null,
    problem:
      'Engineering teams waste thousands of hours manually triaging pull requests, routing tickets to the wrong developers, investigating repetitive vulnerabilities, and missing subtle regressions. Traditional AI code review tools only leave passive comments without writing code, still forcing engineers to context-switch, draft fixes, and manually configure test suites.',
    description:
      'An autonomous AI co-worker that orchestrates GitHub PR workflows, enforces release gates, remediates vulnerabilities, synthesizes unit tests, and delivers executive ROI analytics. Built for the IBM AI Builders Challenge, MergeMaster AI analyzes PR diffs, executes multi-agent decision trees, enforces enterprise policies, and pushes automated remediation commits directly to repository branches.',
    architecture: [
      'Stateful LangGraph Multi-Agent Pipeline: Orchestrates an end-to-end graph workflow (extract_diff → analyze_changes with Semantic RAG → route_reviewers → committer_agent → enforce_gate → record_result) powered by IBM Granite 3.0/3.1 Code & Instruct LLMs.',
      'Autonomous Committer Agent: Directly drafts surgical code corrections for detected vulnerabilities (SQL injections, exposed credentials, unhandled exceptions) and commits fixes directly to the PR branch via PyGithub.',
      'Semantic RAG & Historical Memory: Vector indexing over historical repository reviews, past merge decisions, and recurring CVEs to ground code evaluations in institutional learnings.',
      'Reactive Real-Time Telemetry: Convex Cloud WebSocket layer syncing live agent audit logs, PR gate statuses, and executive metrics to a TanStack Start & React 19 frontend.',
      'Automated Test Synthesizer & Policy Engine: One-click generation of comprehensive PyTest/Vitest test suites with customizable enterprise policy enforcement and dynamic file-pattern reviewer routing.',
    ],
    features: [
      'Autonomous Vulnerability Remediation & Direct PR Commits',
      'Interactive PR Copilot Chat for Live Diff Q&A',
      'One-Click Autonomous Unit Test Suite Synthesizer',
      'Semantic RAG Memory of Historical Code Reviews',
      'Custom Organizational Security Policy Engine',
      'Smart File-Pattern Reviewer Routing & Gate Enforcer',
      'Executive ROI & Developer Hours Saved Analytics Dashboard',
    ],
    techStack: [
      'LangGraph',
      'IBM Granite',
      'FastAPI',
      'Python',
      'Convex',
      'PyGithub',
      'WorkOS',
      'React 19',
      'Tanstack Start',
      'Tailwind CSS v4',
      'Docker',
      'Shadcn UI',
    ],
    image: '/projects/mergemaster.png',
    demoLink: 'https://merge-master-ai.vercel.app',
    repoLink: 'https://github.com/elli1216/MergeMasterAI',
    category: category.HACKATHON,
    certificate: '/certificates/aug-ai-builders-challenge.png',
  },
  {
    title: 'QuickRoute',
    position: 'Full Stack Developer',
    collaborators: null,
    problem:
      'Frontend engineers and QA testers often get blocked waiting for backend APIs to be designed, deployed, or stabilized. Existing mocking tools (Postman Mock, WireMock, Mockoon) are either paid, complex, require account sign-ups, or demand tedious local installations, creating friction in fast-paced development cycles.',
    description:
      'An instant REST API mock server that lets developers visually construct endpoints, upload schema definitions, and receive live, callable HTTP URLs within seconds. Built with a Spring Boot reactive dispatcher backend and a TanStack Start edge frontend on Cloudflare Workers, supporting dynamic route registration, simulated network latency, and path variable substitution.',
    architecture: [
      'Spring Boot Dynamic Route Dispatcher: Custom Spring Boot request handler evaluating wildcard URI patterns (/mock/{mockId}/**), interpolating path variables (:id) into JSON response templates, and simulating network delays.',
      'Dual-Environment Persistence Layer: Utilizes Spring Data JPA with PostgreSQL in production for persistent mock state and in-memory H2 database during development.',
      'Automated Lifecycle & Rate Limiting: Built-in 7-day TTL expiration daemon and IP-based rate-limiting servlet filters to prevent resource exhaustion without requiring user logins.',
      'Edge-Deployed Frontend on Cloudflare Workers: TanStack Start SSR/SPA client compiling TypeScript route configurations and validating JSON payloads with sub-second response times.',
    ],
    features: [
      'Visual Route Builder for GET, POST, PUT, DELETE, & PATCH',
      'Instant Callable Endpoints (https://host/mock/{id}/path)',
      'Configurable Network Latency & Response Delay Simulation',
      'Dynamic Path Variable Substitution (:id in Body)',
      'Zero Sign-Up & 7-Day Automatic Mock TTL Expiry',
      'Edge-Deployed on Cloudflare Workers with Spring Boot Core',
    ],
    techStack: [
      'Spring Boot',
      'Java',
      'PostgreSQL',
      'Hibernate',
      'Tanstack Start',
      'React',
      'Cloudflare Workers',
      'Docker',
      'Tailwind CSS',
      'Shadcn UI',
    ],
    image: '/projects/quickroute.png',
    demoLink: 'https://quick-route.app/',
    repoLink: 'https://github.com/elli1216/QuickRoute-Web',
    category: category.PERSONAL,
  },
  {
    title: 'Code3270',
    position: 'Developer',
    collaborators: null,
    problem:
      'Learning and validating enterprise COBOL and JCL traditionally requires heavy z/OS mainframe emulators, complex terminal setups (TN3270), and slow feedback cycles. This steep configuration barrier prevents developers and students from efficiently practicing mainframe programming in a zero-setup environment.',
    description:
      'A frictionless, web-based platform designed to help developers learn, write, and validate COBOL and Job Control Language (JCL) directly in the browser with zero emulators, accounts, or server dependencies. Features split-screen markdown tutorials, Monaco Editor integration with a retro "Green Screen" theme, and 100% client-side validation.',
    architecture: [
      'Strategy (Rule-Based) Design Pattern: Both COBOL and JCL linters decouple individual syntax validations (Sequence Area boundaries, Area A/B division rules, Undefined Variables, JCL Continuation cards) into independent, reusable rule objects conforming to strict CobolRule and JclRule interfaces.',
      'Open-Closed Principle (OCP): Core linting engines iterate over registered rule arrays (ALL_COBOL_RULES & ALL_JCL_RULES). Adding new syntax checks requires zero modifications to the core parser loop, enabling seamless extension.',
      'Single Source of Truth Specs: Positional column numbers (Cols 1-6 Sequence, Col 7 Indicator, Cols 8-11 Area A, Cols 12-72 Area B), allowed clauses, and reserved mainframe words are centralized in standardized constants (COBOL_SPECS & JCL_SPECS).',
      'Zero-Latency Client-Side Execution: Validation runs entirely in the browser runtime with localStorage persistence for progress tracking, guaranteeing code privacy and instant feedback.',
    ],
    features: [
      'Instant In-Browser COBOL & JCL Syntax Validation',
      'Interactive Split-Screen Markdown Tutorials',
      'Monaco Editor with Retro Mainframe "Green Screen" Theme',
      '100% Client-Side Privacy with Zero Server Dependencies',
    ],
    techStack: [
      'React',
      'TypeScript',
      'Tanstack Start',
      'Monaco Editor',
      'Tailwind CSS',
      'Shadcn UI',
      'Strategy Design Pattern',
    ],
    image: '/projects/code3270.png',
    demoLink: 'https://code3270.vercel.app/',
    repoLink: 'https://github.com/elli1216/code3270',
    category: category.PERSONAL,
  },
  {
    title: 'AstriaAI',
    position: 'Full Stack & AI Engineer',
    hackathonTitle: 'IBM Bob TechXchange Dev Day Hackathon',
    collaborators: null,
    problem:
      'Merging a pull request can silently break downstream services. A change to a single API contract or database field often ripples through multiple routes, consumers, and models that existing unit tests never cover, so regressions only surface in production after deploy.',
    description:
      'An autonomous PR Blast-Radius Analyzer & Regression Test Generator that ingests a pull request diff, parses API contracts and database schemas, then coordinates three parallel IBM Granite subagents to trace the full blast radius, construct edge-case payloads, synthesize regression tests, execute them in a sandbox, and post a complete "Blast Radius & Safety Report" directly to the GitHub PR.',
    architecture: [
      'Three-Parallel IBM Granite Subagents: A Massive Parallel pipeline orchestrating the Granite 20B Code Blast-Radius Tracer (ast + regex diff tracing), the Granite 3 8B Instruct Fuzz Constructor (boundary/adversarial payloads), and the Granite Code Test Synthesizer (pytest/vitest generation).',
      'FastAPI Multi-Agent Orchestrator: Central backend assembling context (diff + openapi + db_schema) and coordinating the blast-radius tracer, fuzz constructor, test synthesizer, sandbox executor, and remediation agent into a single analysis pass.',
      'Sandboxed Test Execution: Runs synthesized pytest/vitest suites in isolated subprocess sandboxes to capture regressions and feed results into the remediation agent.',
      'Auto-Remediation & 1-Click Patches: The Granite Code Remediation Agent reads the failing test output and generates unified-diff patches that fix the downstream consumer.',
      'Real-Time Sync via Convex: Live analysis status, blast-radius impact graph, and PR comments streamed to a TanStack Start + React 19 dashboard through Convex real-time subscriptions and GitHub OAuth.',
    ],
    features: [
      'Blast-Radius Tracing Across Routes, Services & DB Models',
      'Edge-Case & Adversarial Payload Construction (null, type mismatch, SQLi)',
      'Executable pytest/vitest Regression Test Synthesis',
      'Sandboxed Test Execution & Failure Capture',
      '1-Click Patch Generation for Downstream Consumers',
      'Automatic GitHub PR "Blast Radius & Safety Report" Comment',
      'Interactive React Flow Blast-Radius Impact Graph',
    ],
    techStack: [
      'IBM Granite',
      'IBM watsonx.ai',
      'FastAPI',
      'Python',
      'Convex',
      'React 19',
      'Tanstack Start',
      'Tanstack Router',
      'React Flow',
      'Zustand',
      'Tailwind CSS v4',
      'GitHub App',
      'AST Parsing',
    ],
    image: '/projects/astria-logo.png',
    demoLink: 'https://github.com/apps/astriaaiapp',
    repoLink: 'https://github.com/elli1216/AstriaAI',
    category: category.HACKATHON,
  },
  {
    title: 'WhatsApp AI Notification Router',
    position: 'AI Developer',
    hackathonTitle: 'HackerRank Orchestrate 24-hour Hackathon',
    collaborators: null,
    placement: '401st Place',
    placementOutOf: '1983 contestants',
    problem:
      'WhatsApp streams are overwhelmed with noisy notifications—family chats, school updates, work threads, promotions, poster screenshots, and voice notes all compete equally for attention. Treating every message identically causes critical updates to get missed while scam and spam interruptions erode user attention. The system must process multimodal streams and make personalized routing decisions (notify, digest, or mute) while deterministically muting scam or phishing threats.',
    description:
      'A complete AI-powered Message Notification Router for WhatsApp that classifies incoming multimodal messages (text, image posters, voice notes) into notify, digest, or mute. It personalizes decisions by fusing user notification behaviors, group roles, business trust signals, and historical interaction events into a context-aware prompt, while a heuristic retrieval engine surfaces the 3 most relevant historical messages with real user reactions as evidence. Runs on Gemini API with temperature-0 structured JSON validation and an incremental, resumable batch execution pipeline.',
    architecture: [
      'Context Assembly & O(1) Data Layer: Loads relational datasets (user behaviors, group metadata, membership roles, business trust signals, and historical reaction events) into indexed DataFrames for rapid, zero-overhead context retrieval.',
      'Heuristic Evidence Retrieval Engine: Ranks and surfaces the top-3 most relevant historical messages and actual user reactions (opened, replied, dismissed, muted, reported) without embedding overhead, enabling the LLM to cite genuine message IDs as evidence.',
      'Native Multimodal Ingestion & Vision/Audio Support: Directly attaches images (posters, screenshots) and audio bytes (voice notes) to the Gemini model alongside text payloads, with hardened prompt-injection defense.',
      'Deterministic Schema Enforcement: Executes on Gemini API with temperature 0 and strict Pydantic v2 JSON schema validation (action, message_type, reason, confidence, evidence_message_ids).',
      'Incremental & Resumable Batch Pipeline: Production processor with 4.5s request throttling (15 RPM free-tier limit), 60s backoff for 429 rate limits, and row-by-row atomic writes to output.csv.',
    ],
    features: [
      'Multimodal Message Routing (Text, Image Posters, Voice Notes)',
      'Personalized Decision Engine (Notify, Digest, or Mute)',
      'Deterministic Scam, Phishing, and Chain-Letter Muting',
      'Prompt-Injection Resilient Architecture',
      'Historical Evidence Citation Engine (Top-3 Message IDs)',
      'Resumable Batch Processor with Adaptive Rate-Limit Backoff',
    ],
    metrics: [
      { label: 'Action Accuracy', value: '96.67%' },
      { label: 'Type Accuracy', value: '93.33%' },
      { label: 'Messages Routed', value: '110/110' },
    ],
    techStack: [
      'Python',
      'Gemini Multimodal API',
      'Pydantic v2',
      'Pandas',
      'Heuristic Evidence Retrieval',
      'Batch Pipeline Architecture',
    ],
    image:
      'https://placehold.co/800/black/white?text=Message+Notification+Router+(Hackathon)&font=playfair-display',
    // demoLink: "",
    repoLink: 'https://github.com/elli1216/message-notification-router',
    category: category.HACKATHON,
    certificate: '/certificates/hackerrank.png',
  },
  {
    title: 'PlotWeaver AI',
    position: 'Full Stack Lead',
    hackathonTitle: 'IBM AI Builders Challenge (July Edition)',
    theme:
      "AI is transforming how people create content, tell stories, design experiences, and bring ideas to life. Creative industries are driven by imagination and expression, but the creative process is often constrained by time-consuming production workflows, technical complexity, limited access to advanced tools, and challenges turning ideas into finished outputs quickly. As demand for digital content continues to grow, creators are expected to produce more, faster, and across multiple formats than ever before. Your challenge is to build AI-powered tools that transform how creative work is imagined, produced, and experienced. Whether you're creating AI creative partners, storytelling tools, multimodal experiences, creative ideation platforms, or personalized creative assistants, your solution should demonstrate how AI can expand creative potential and redefine creative workflows.",
    collaborators: [
      {
        name: 'Karan Munreja',
        link: 'https://www.linkedin.com/in/karan-munreja/',
      },
      {
        name: 'Michael Omijie',
        link: 'https://www.linkedin.com/in/michaelomijie/',
      },
    ],
    problem:
      "Writing complex novels, screenplays, or game lore is notoriously difficult. Authors struggle with continuity drift across hundreds of pages, tracking fragile world-building rules (magic constraints, tech limits, timelines) across dozens of chapters, while standard AI writing tools attempt to ghostwrite generic prose that dilutes the author's unique voice rather than fixing plot logic.",
    description:
      'An AI-powered visual storytelling workspace and creative partner built for the IBM AI Builders Challenge (July Edition). PlotWeaver replaces wall-to-wall text with an interactive node-based story canvas where authors map narrative beats, characters, and world rules. Its multi-agent AI auditor continuously checks for timeline contradictions, character logic breaks, and world-building rule violations without ghostwriting.',
    architecture: [
      'Infinite Node-Based Graph Engine: Built on React Flow with custom node types (Beats, Characters, Locations, Objects, World Rules) and auto-layout algorithms for dynamic spatial storytelling.',
      'Document Parsing with IBM Docling & Granite: Automated manuscript and PDF ingestion (up to 5 pages) extracting characters, locations, and plot events into graph nodes with entity deduplication.',
      'Multi-Agent Narrative Consistency Auditor: FastAPI backend executing IBM watsonx / Granite LLMs to perform multi-hop graph traversals, flagging chronological paradoxes and world rule breaks.',
      'Hierarchical Export Engine: Translates non-linear visual story graphs into structured, chapter-by-chapter chronological outlines downloadable in .txt format.',
      'Relational State & Canvas Persistence: Supabase database tracking canvas graph states, node metadata, and user project histories.',
    ],
    features: [
      'Interactive Infinite Story Canvas with 1-Click Auto Layout',
      'Automated Manuscript PDF & Text Ingestion (IBM Docling)',
      'Smart Entity Extraction & Canvas Node Deduplication',
      'AI Continuity & World-Building Rule Violation Checker',
      'Chronological Structured Chapter Outline Exporter',
      'Multi-Node Entity Relationship Mapping (Beats, Characters, Rules)',
    ],
    techStack: [
      'React',
      'React Flow',
      'FastAPI',
      'IBM watsonx',
      'IBM Docling',
      'IBM Granite',
      'Supabase',
      'Tanstack Router',
      'Tanstack Query',
      'Tailwind CSS',
      'Shadcn UI',
    ],
    image: '/projects/plotweaver.png',
    demoLink: 'https://youtu.be/kRZ4yRUUrDg',
    repoLink: 'https://github.com/IBMPlotWeaver/plotweaver',
    category: category.HACKATHON,
    certificate: '/certificates/IBMAIBuildersJuly.png',
  },
  {
    title: 'EntityForge',
    position: 'Developer',
    collaborators: null,
    problem:
      'Setting up a Spring Boot backend with JPA/Hibernate is tedious, repetitive, and error-prone. Developers face friction manually translating Entity Relationship Diagrams (ERDs) into compilable Java classes, correctly configuring complex relational mappings (@OneToMany, @ManyToOne, @JoinColumn), and writing matching Flyway DDL migration scripts.',
    description:
      'A 100% client-side, zero-latency visual database modeling tool that transforms visual entity-relationship diagrams into production-ready Spring Boot JPA models and Flyway SQL migrations. Operates as a pure in-browser data-transformation pipeline with real-time split-screen code generation, URL-based state contracts, and in-memory Maven zip bundling.',
    architecture: [
      'URL as Single Source of Truth: State contract defined and validated via Zod schema directly in URL search parameters (TanStack Router), enabling shareable workspace URLs, browser undo/redo history, and background localStorage synchronization.',
      'Reactive React Flow Canvas: Custom EntityNode components with dynamic field definitions, primary key toggles, and directional handles that synchronize node/edge mutations to URL state with zero latency.',
      'Stateless Code Generation Pipeline: Modular TypeScript string transformation engines (jpaGenerator.ts, relationshipParser.ts, ddlGenerator.ts) compiling AST-like node/edge schemas into clean Java classes and valid Flyway/Liquibase DDL.',
      'In-Memory Maven Zip Compiler: Uses JSZip to scaffold standard Spring Boot directory hierarchies (src/main/java/domain, src/main/resources/db/migration) and triggers instant native browser downloads with zero backend processing.',
    ],
    features: [
      'Interactive Drag-and-Drop Entity Canvas (React Flow)',
      'Real-Time Spring Boot JPA & Hibernate Code Generation',
      'Automated Flyway & Liquibase DDL Migration Generator',
      'Shareable Workspace via URL State Synchronization (Zod)',
      'Split-Screen Live Code Previews (Java / SQL / JSON)',
      '1-Click In-Memory Maven Project ZIP Scaffolding (JSZip)',
    ],
    techStack: [
      'React',
      'React Flow',
      'TypeScript',
      'Tanstack Router',
      'Tanstack Query',
      'Zod',
      'JSZip',
      'Tailwind CSS',
      'Shadcn UI',
    ],
    image: '/projects/entityforge.png',
    demoLink: 'https://entityforge.degf.workers.dev/',
    repoLink: 'https://github.com/elli1216/entityforge',
    category: category.PERSONAL,
  },
  {
    title: 'BulSU OSAS Grievance and Response Management Portal',
    position: 'Full Stack Developer',
    collaborators: [
      {
        name: 'Mico Cerbito',
        link: 'https://www.linkedin.com/in/mico-cerbito/',
      },
      {
        name: 'Romeo Quiñones',
        link: 'https://www.linkedin.com/in/romeo-m-quinones-jr/',
      },
      {
        name: 'Enrico Tienzo',
        link: 'https://www.linkedin.com/in/chainsaw-353350379/',
      },
    ],
    problem:
      'The university Office of Student Affairs and Services (OSAS) relied entirely on manual paperwork and physical office visits for filing grievances and tracking offenses. This created severe resolution bottlenecks, lack of student transparency, fragmented cross-department communication across colleges, and untracked administrative sanctions.',
    description:
      'A multi-role enterprise web portal that digitizes and centralizes end-to-end grievance management, offense tracking, and administrative sanctions across all Bulacan State University colleges. Architected using Feature-Sliced Design (FSD) with role-based dashboards for Students, College Admins, and OSAS Super Admins, backed by Supabase and end-to-end Playwright test suites.',
    architecture: [
      'Feature-Sliced Design (FSD): Modular domain-driven frontend architecture organized into discrete layers (features/admin, features/college-admin, features/user, features/auth, features/_common) ensuring strict decoupling and maintainability.',
      'Dual-State Management Pattern: Combines Zustand for client session state and global UI stores with TanStack Query for optimistic server-state mutations and cache invalidation.',
      'Multi-Tenant RBAC & Route Guards: Multi-level route protection in React Router DOM v7 separating Public/Student portals from Super Admin (/admin/student-affairs) and College-scoped Admin (/admin/college/:college) views.',
      'Type-Safe Form & Dispute Validation: Robust form validation pipeline powered by React Hook Form + Zod, guaranteeing strict schema integrity for evidence uploads and complaint routing.',
      'Full-Stack Automated Test Suite: Comprehensive unit/component testing with Vitest and mission-critical end-to-end user journey test suites automated using Playwright.',
    ],
    features: [
      'Public Student Portal for Complaint Submissions & Live Status Tracking',
      'OSAS Super Admin Centralized Case & College Department Routing',
      'College-Specific Administrative Dashboards & Investigation Tools',
      'Disciplinary Offense, Sanction, & Hearing Schedule Manager',
      'Digital Evidence Attachment & Automated Endorsement Pipeline',
      'Automated E2E Test Coverage with Playwright & Vitest',
    ],
    techStack: [
      'React 19',
      'TypeScript',
      'Vite',
      'Supabase',
      'Tanstack Query',
      'Zustand',
      'React Hook Form',
      'Zod',
      'Playwright',
      'Vitest',
      'Tailwind CSS v4',
      'DaisyUI',
    ],
    image: '/projects/osas.png',
    repoLink: '',
    demoLink: 'https://www.osascomplaints.dev/',
    category: category.CAPSTONE,
  },
  {
    title: 'STC Performing Arts Center Website',
    position: 'Full Stack Developer',
    collaborators: null,
    problem:
      'The studio managed its class registrations, coach bookings, studio rentals, and payment collections through manual Google Forms and direct messaging. This led to capacity overbooking, manual payment verification bottlenecks, payment reconciliation errors, and difficult student schedule coordination as the business expanded.',
    description:
      'A full-scale commercial web application and administrative ERP for the STC Performing Arts Center. Built with Next.js (App Router) and TypeScript, featuring a public-facing booking portal with GSAP animations, an administrative dashboard for managing classes, events, students, and coaches, integrated PayMongo payment processing, and Google Drive API for GCash proof-of-payment storage.',
    architecture: [
      'Next.js App Router & Route Groups: Decouples public customer booking flows (main) from protected administrative portals (admin) with Next.js Turbopack compilation.',
      'Feature-Sliced Domain Organization: Organized into discrete feature directories (src/features/home, src/features/admin/coaches, src/features/admin/classes, src/features/common) with reusable custom fetchers.',
      'Dual-State Architecture: Zustand manages global client-side checkout and UI states, while React Query (TanStack Query v5) handles server-state caching and Supabase synchronization.',
      'Automated Payment & Storage Pipeline: Seamless checkout flow via PayMongo gateway paired with Google Drive API and Supabase Storage for automatic GCash proof-of-payment archival.',
      'Type-Safe Forms & Motion Design: Validated with React Hook Form + Zod schema validation, Radix UI headless components, and bespoke GSAP animations.',
    ],
    features: [
      'Interactive Class, Workshop, & Studio Rental Booking Portal',
      'Comprehensive Admin Dashboard for Classes, Events, & Students',
      'PayMongo Payment Gateway Integration (Credit Cards & E-Wallets)',
      'Google Drive API & Supabase Storage for GCash Receipt Uploads',
      'Coach Scheduling, Capacity Management, & Attendance Tracking',
      'Bespoke GSAP Animations & Radix UI Design System',
    ],
    techStack: [
      'Next.js',
      'TypeScript',
      'React',
      'PayMongo',
      'Supabase',
      'Google Drive API',
      'Tanstack Query v5',
      'Zustand',
      'GSAP',
      'Tailwind CSS',
      'Radix UI',
      'Zod',
    ],
    image: '/projects/stc.png',
    repoLink: '',
    demoLink: 'https://stcpacv3.vercel.app/',
    category: category.FREELANCE,
  },
  {
    title: 'Tic-a-Pic Photobooth',
    position: 'Full Stack Developer',
    collaborators: [
      {
        name: 'Paolo Angelo',
        link: 'https://www.linkedin.com/in/paolo-angelo/',
      },
    ],
    problem:
      'Traditional physical photobooths are expensive and inconvenient for everyday social moments, while existing digital photobooth web apps force users through tedious account registrations, inject invasive watermarks, or suffer from laggy in-browser image rendering.',
    description:
      'An interactive, no-login web-based photobooth that turns any mobile device or laptop camera into an instant photo studio. Users capture multi-frame strips, customize layouts with stickers and retro borders, and export high-resolution print-ready photo strips with zero account friction.',
    architecture: [
      'Client-Side Canvas Processing Engine: High-performance HTML5 Canvas and WebRTC camera stream pipeline rendering live multi-frame captures, sticker compositing, and print-resolution image exports.',
      'Zero-Auth Session Architecture: Ephemeral session management using client-generated UUIDs and localStorage caching, eliminating onboarding drop-off and ensuring total user privacy.',
      'Serverless Edge Backend: Next.js App Router running on Vercel Edge Runtime for lightweight token verification and dynamic layout metadata dispatch.',
      'Cloud Asset Distribution: Supabase Storage CDN serving high-resolution photobooth border templates, sticker packs, and downloadable PDF print guides.',
    ],
    features: [
      'Instant WebRTC Camera Multi-Frame Photo Capture',
      'Interactive Sticker & DIY Layout Customizer (HTML5 Canvas)',
      'Free & Premium Photobooth Strip Layouts (Classic 4-Cut, Split-Heart)',
      'Zero Login & Frictionless Anonymous Session State',
      'Print-Ready High-Res PNG & PDF Print Guide Exporter',
      'Mobile-First Responsive Interface with DaisyUI & Tailwind',
    ],
    techStack: [
      'Next.js',
      'TypeScript',
      'React',
      'HTML5 Canvas API',
      'WebRTC Camera API',
      'Supabase',
      'Tailwind CSS',
      'DaisyUI',
      'Vercel Edge',
    ],
    image: '/projects/ticapic.png',
    repoLink: 'https://github.com/elli1216/Tic-a-Pic',
    // demoLink: "https://tic-a-pic.vercel.app/",
    category: category.PERSONAL,
  },
  {
    title: 'Jobinator',
    position: 'Full Stack Developer',
    collaborators: null,
    problem:
      'Managing dozens of active job applications, recruiter communications, interview stages, and salary offers across fragmented spreadsheets and disparate job boards is messy and error-prone, making it easy to miss follow-ups and deadlines during the recruitment cycle.',
    description:
      'A full-stack job hunt CRM application built with TanStack Start, React 19, and Prisma ORM. Centralizes job application lifecycles, interview timelines, and recruiter notes with type-safe server-side rendering, Neon serverless PostgreSQL, Clerk authentication, and TanStack Query state caching.',
    architecture: [
      'TanStack Start Full-Stack SSR: Type-safe file-based routing and server-side data loaders (src/routes) delivering fast initial page loads and seamless client transitions.',
      'Serverless PostgreSQL with Prisma ORM: Neon serverless PostgreSQL backend managed through Prisma schemas (prisma/schema.prisma) with automated database migrations and type-safe query generation.',
      'TanStack Query Server-State Caching: Optimistic UI mutations, automatic background refetching, and real-time cache synchronization for application state updates.',
      'Secure Clerk Multi-Tenant Authentication: User session management and identity lifecycle protecting personal job pipelines and private candidate notes.',
      'Netlify Serverless Deployment: Continuous integration pipeline with automated Vite build optimization and edge function execution.',
    ],
    features: [
      'End-to-End Job Application Lifecycle & Status Tracking',
      'Interview Round & Recruiter Contact Log Management',
      'Type-Safe Server-Side Rendered Routes (TanStack Start)',
      'Serverless PostgreSQL Persistence via Prisma ORM & Neon',
      'Clerk Multi-Tenant Authentication & Session Guarding',
      'Responsive Dashboard with Tailwind CSS & Shadcn UI',
    ],
    techStack: [
      'Tanstack Start',
      'React',
      'TypeScript',
      'Prisma',
      'Neon',
      'Clerk',
      'Tanstack Router',
      'Tanstack Query',
      'Tailwind CSS',
      'Shadcn UI',
      'Netlify',
    ],
    image: '/projects/jobinator.png',
    repoLink: 'https://github.com/elli1216/Jobinator',
    category: category.PERSONAL,
  },
  {
    title: 'ByteBazaar',
    position: 'Full Stack Developer',
    collaborators: [
      {
        name: 'Mico Cerbito',
        link: 'https://www.linkedin.com/in/mico-cerbito/',
      },
      {
        name: 'Romeo Quiñones',
        link: 'https://www.linkedin.com/in/romeo-m-quinones-jr/',
      },
      {
        name: 'Enrico Tienzo',
        link: 'https://www.linkedin.com/in/chainsaw-353350379/',
      },
    ],
    problem:
      'Building a full-featured e-commerce ecosystem requiring hierarchical product categorization, user authentication, shopping carts, and inventory control, while exploring server-side XML-based data persistence and DOM parsing without relying on standard SQL/NoSQL databases.',
    description:
      'A full-stack hardware and computer accessories e-commerce web platform presented in Web Systems and Technologies. Features customer catalog browsing, shopping carts, and order tracking alongside an administrative back-office with Multer image uploads and stock management, powered by an Express.js backend utilizing XML data persistence via xml2js.',
    architecture: [
      'XML File-Based Persistence: Custom server-side data storage layer managing schemas for products.xml, users.xml, orders.xml, cart.xml, and categories.xml parsed and updated via xml2js.',
      'Modular Express.js REST API: Controller-route architecture handling product catalog CRUD, image uploads via Multer middleware, and order lifecycle management.',
      'Firebase Authentication & RBAC: User authentication with reCAPTCHA verification, 30-day token cookies, and domain-based role guards granting admin dashboard access to authorized administrators.',
      'React 19 & Framer Motion UI: Vite-powered frontend utilizing Tailwind CSS and DaisyUI components with smooth Framer Motion page transitions and responsive cart drawers.',
    ],
    features: [
      'Categorized Hardware Catalog (Laptops, Components, Peripherals)',
      'Shopping Cart Management & Real-Time Quantity Adjustments',
      'Order Placement & Historical Status Tracking',
      'Admin Dashboard for Product Catalog CRUD & Stock Control',
      'Multi-Part Form Data & Image Uploads (Multer)',
      'Firebase Authentication with reCAPTCHA Verification',
    ],
    techStack: [
      'React 19',
      'TypeScript',
      'Node.js',
      'Express.js',
      'XML / xml2js',
      'Firebase Auth',
      'Tailwind CSS',
      'DaisyUI',
      'Framer Motion',
      'Multer',
      'Vite',
    ],
    image: 'https://placehold.co/800/purple/white?text=ByteBazaar&font=playfair-display',
    repoLink: 'https://github.com/elli1216/Bytebazaar',
    category: category.ACADEMIC,
  },
  {
    title: 'School Enrollment System',
    position: 'Full Stack Java Developer',
    collaborators: [
      {
        name: 'Paolo Angelo',
        link: 'https://www.linkedin.com/in/paolo-angelo/',
      },
      {
        name: 'James Godoy',
        link: 'https://www.linkedin.com/in/jamessamuelgodoy/',
      },
      {
        name: 'Ervin Ilarde',
        link: 'https://www.linkedin.com/in/ervinilarde/',
      },
      {
        name: 'Ryan Gomez',
        link: 'https://ph.linkedin.com/in/ryan-carlo-gomez-4aa035292',
      },
    ],
    problem:
      'Educational institutions face operational friction and data inconsistencies when manually handling student enrollments, subject add/drop requests, faculty assignments, and grade records across paper-based workflows.',
    description:
      'A comprehensive Java-based desktop application for managing school enrollment and academic administration presented in Advanced Programming. Features separate, role-segregated desktop interfaces for students (subject add/drop, grade reports, profile tracking) and administrators (student/faculty CRUD, course and section management, grade recording), powered by an MVC architecture and Microsoft SQL Server.',
    architecture: [
      'MVC & DAO Architectural Patterns: Clear structural separation of Model entities (Student, Faculty, Course, Subject, Section, Grades), View interfaces (StudentDashboard, Home, StudentEnrollment), and Data Access Object (DAO) layers.',
      'Singleton Database Connection: Centralized DBConnection utility implementing the Singleton pattern to manage pooled JDBC connections to Microsoft SQL Server with integrated security.',
      'Relational Database Schema: Microsoft SQL Server database enforcing foreign key relationships and referential integrity across student records, faculty departments, and subject enrollment tables.',
      'Role-Segregated Java Swing Desktop GUI: Specialized, state-managed GUI views designed in NetBeans with event-driven listeners for administrative operations and student enrollment workflows.',
    ],
    features: [
      'Student Self-Service Portal (Subject Add/Drop & Grade Viewing)',
      'Administrator Command Center (Student & Faculty CRUD Operations)',
      'Academic Curriculum & Course/Section Configuration',
      'Faculty Department & Subject Assignment Manager',
      'Academic Grade Recording & Performance Tracking',
      'Centralized JDBC Connection Pool with Singleton Pattern',
    ],
    techStack: [
      'Java',
      'Java Swing',
      'JDBC',
      'SQL Server',
      'MVC Architecture',
      'DAO Pattern',
      'Agile Development',
    ],
    image:
      'https://placehold.co/800/darkblue/white?text=School+Enrollment+System&font=playfair-display',
    repoLink: 'https://github.com/elli1216/School-Enrollment-System',
    category: category.ACADEMIC,
  },
];

export const SKILL_DATA: SkillItem[] = [
  { name: 'Java', category: 'backend', icon: 'java', render: true },
  { name: 'COBOL', category: 'backend', icon: '', render: true },
  { name: 'Spring Boot', category: 'backend', icon: 'spring', render: true },
  { name: 'ReactJS', category: 'frontend', icon: 'react', render: true },
  { name: 'Tailwind CSS', category: 'frontend', icon: 'tailwindcss', render: true },
  { name: 'NextJS', category: 'frontend', icon: 'nextjs2', render: true },
  { name: 'Tanstack', category: 'frontend', icon: 'tanstack2', render: true },
  { name: 'TypeScript', category: 'frontend', icon: 'typescript', render: true },
  { name: 'PostgreSQL', category: 'backend', icon: 'postgresql', render: true },
  { name: 'NodeJS', category: 'backend', icon: 'nodejs', render: true },
  { name: 'Docker', category: 'tools', icon: 'docker', render: true },
  { name: 'Git', category: 'tools', icon: 'git', render: true },
  { name: 'JavaScript', category: 'frontend', icon: 'js' },
  { name: 'HTML5', category: 'frontend', icon: 'html5' },
  { name: 'CSS3', category: 'frontend', icon: 'css3' },
  { name: 'SQL', category: 'backend', icon: 'mysql' },
  { name: 'JCL', category: 'backend', icon: '' },
  { name: 'ExpressJS', category: 'backend', icon: 'expressjs' },
  { name: 'GitHub', category: 'tools', icon: 'github' },
  { name: 'Bash', category: 'tools', icon: 'bash' },
  { name: 'Python', category: 'backend', icon: 'python' },
  { name: 'Prisma', category: 'backend', icon: 'prisma' },
  { name: 'OpenAI', category: 'tools', icon: 'openai' },
  { name: 'AWS', category: 'tools', icon: 'aws' },
  { name: 'Cloudfare', category: 'tools', icon: 'cloudfare' },
  { name: 'Langchain', category: 'tools', icon: 'langchain' },
  { name: 'Gemini', category: 'tools', icon: 'gemini' },
  { name: 'Claude', category: 'tools', icon: 'claude' },
  { name: 'Vite', category: 'frontend', icon: 'vitejs' },
];

export const certificates = [
  {
    src: '/certificates/aws_cloud.png',
    issuer: 'DataCamp',
    alt: 'AWS Cloud Practitioner (CLF-C02)',
    href: 'https://www.datacamp.com/completed/statement-of-accomplishment/track/37aa7cab72a12269629abcc4c662ac4af70fbbc1?utm_medium=organic_social&utm_campaign=sharewidget&utm_content=soa',
  },
  {
    src: '/certificates/assocai.png',
    issuer: 'DataCamp',
    alt: 'Associate AI Engineer for Developers',
    href: 'https://www.datacamp.com/completed/statement-of-accomplishment/track/185ae827af3fb597750701fb515e41c0c01cff74',
  },
  {
    src: '/certificates/dockerk8.png',
    issuer: 'DataCamp',
    alt: 'Containerization and Virtualization with Docker and Kubernetes',
    href: 'https://www.datacamp.com/completed/statement-of-accomplishment/track/bb778aa8f1e1e41952d9f7f335fdc69bd8d040f6?utm_medium=organic_social&utm_campaign=sharewidget&utm_content=soa',
  },
  {
    src: '/certificates/javadev-1.png',
    issuer: 'DataCamp',
    alt: 'Java Developer',
    href: 'https://www.datacamp.com/completed/statement-of-accomplishment/track/d24f11d25eef873a334251eaac3d132d5e082d51',
  },
  {
    src: '/certificates/mainframedeveloper.jpg',
    issuer: 'IBM',
    alt: 'IBM Mainframe Developer',
    href: 'https://www.coursera.org/account/accomplishments/specialization/certificate/GTA3SGF8S3NV',
  },
  {
    src: '/certificates/IBMZALLSTAR.jpg',
    issuer: 'IBM via Credly',
    alt: 'All Star Badge - IBM Z Xplore',
    href: 'https://www.credly.com/badges/9c95a33b-7c50-434b-b7eb-eba86e1c1c0e/linked_in_profile',
  },
  {
    src: '/certificates/EnterpriseCOBOLProgrammingwithVSCode.png',
    issuer: 'IBM via Credly',
    alt: 'Enterprise COBOL Programming with VSCode',
    href: 'https://www.credly.com/badges/9f1d7099-11ed-4ddd-af8f-c296f22c7d4a/linked_in?t=tf4cc7',
  },
  {
    src: '/certificates/advocate.jpg',
    issuer: 'IBM',
    alt: 'IBM Z Advocate',
    href: 'https://www.credly.com/badges/d122ced4-831f-4d44-944e-77c0663ff88b/public_url',
  },
  {
    src: '/certificates/learnintermediatejava.jpg',
    issuer: 'Codecademy',
    alt: 'Learn Intermediate Java',
    href: 'https://www.codecademy.com/profiles/degf/certificates/2624ed9b49bb4d5c994983877e5263f0',
  },
  {
    src: '/certificates/rest_api-1.png',
    issuer: 'HackerRank',
    alt: 'Rest API',
    href: 'https://www.hackerrank.com/certificates/1135784070d0',
  },
  {
    src: '/certificates/springbootfundamentals.png',
    issuer: 'Pluralsight',
    alt: 'Spring Boot Fundamentals',
    href: 'https://app.pluralsight.com/achievements/share/1c045e31-29f3-4a9d-a0f7-6f0db161da6b',
  },
  {
    src: '/certificates/java8.png',
    issuer: 'Pluralsight',
    alt: 'Java 8 Fundamentals',
    href: 'https://app.pluralsight.com/achievements/share/ece26aa5-2f58-4dc6-91aa-6bbad8e143b8',
  },
  {
    src: '/certificates/nextjsproj_page.jpg',
    issuer: 'Udemy',
    alt: 'NextJS Project BootCamp',
    href: 'https://www.udemy.com/certificate/UC-e4312cb7-9b70-4822-ae7a-5270b6759622/',
  },
  {
    src: '/certificates/foundations.jpg',
    issuer: 'Udemy',
    alt: 'Foundations of Web Development',
    href: 'https://www.udemy.com/certificate/UC-47707ddb-68d9-4661-80e1-c54313587553/',
  },
  {
    src: '/certificates/htmlcssjsreact.jpg',
    issuer: 'Udemy',
    alt: 'HTML, CSS, JS, React',
    href: 'https://www.udemy.com/certificate/UC-9e5b5a02-e296-462b-9da7-09af19fb1706/',
  },
  {
    src: '/certificates/CyberThreatManagement.jpg',
    issuer: 'Cisco',
    alt: 'Cyber Threat Management',
    href: 'https://www.credly.com/badges/fedbe3b2-8519-4e22-976e-153dd577c5c7/public_url',
  },
  {
    src: '/certificates/SecurityandConnectivitySupport.jpg',
    issuer: 'Cisco',
    alt: 'Security and Connectovity Support',
    href: 'https://www.credly.com/badges/fb5d7810-4e12-4d93-ab39-0b54c34bc1a5/public_url',
  },
];

export const contactItems = [
  {
    icon: Mail,
    label: 'Email',
    value: 'floresca.darlellisong@gmail.com',
    href: 'mailto:floresca.darlellisong@gmail.com',
  },
  {
    icon: Linkedin,
    label: 'LinkedIn',
    value: 'Darl Ellison Floresca',
    href: 'https://www.linkedin.com/in/darlfloresca/',
  },
  {
    icon: Github,
    label: 'GitHub',
    value: '@elli1216',
    href: 'https://github.com/elli1216',
  },
  {
    icon: Facebook,
    label: 'Facebook',
    value: 'Darl Ellison Floresca',
    href: 'https://www.facebook.com/darlellison/',
  },
];

export const MONTHS = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];
